$:
  vscode:
    - docker:
        build:
          dockerfile: .ide/Dockerfile
          by:
           - .vscode/settings.yml
      runner:
        cpus: 4
      services:
        - vscode
        - docker
      stages:
        - name: ls
          script: ls -la