$:
  vscode:
    - docker:
        image: ${CNB_DOCKER_REGISTRY}/${CNB_REPO_SLUG_LOWERCASE}:env
        volumes:
            - ./backend/.venv:rw
            - ./backend/app/static:rw
            - ./frontend/node_modules:rw
      runner:
        cpus: 8
      services:
        - vscode
        - docker
      stages:
        - name: ls
          script: ls -la
  push:
    - stages:
        - name: sync to github
          imports: https://cnb.cool/pylover/key/-/blob/main/github.yml
          image: tencentcom/git-sync
          settings:
            target_url: https://github.com/pylover7/PyTool.git
            auth_type: https
            username: ${GIT_USERNAME}
            password: ${GIT_ACCESS_TOKEN}

  web_trigger_one:
    - services:
        - docker
      env:
        IMAGE_TAG: ${CNB_DOCKER_REGISTRY}/${CNB_REPO_SLUG_LOWERCASE}:env
      stages:
        - name: docker build
          script: docker build -t ${IMAGE_TAG} . -f .ide/Dockerfile
        - name: docker list
          script: docker images
        - name: docker push
          script: docker push ${IMAGE_TAG}